# Generated by Django 5.1 on 2024-08-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_first_name', models.CharField(max_length=32)),
                ('member_last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('book_author', models.CharField(max_length=64)),
                ('book_year', models.IntegerField()),
                ('book_borrowed', models.BooleanField(default=False)),
                ('book_return_date', models.DateField()),
                ('book_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.member')),
            ],
        ),
    ]
